String info_html = ""
"<!DOCTYPE html>\n"
"    <head>\n"
"       <title>HoloBOT</title>\n"
"       <link rel='stylesheet' href='style.css'>\n"
"    </head>\n"
"    <html>\n"
"    <body>\n"
"\n"
"        <h1>HOLOBOT</h1>\n"
"        <h2>Last error:</h2>\n"
"        <p>[[[ERROR]]]</p>\n"
"        <h2>Battery:</h2>\n"
"        <p>[[[BATTERY]]] V</p>\n"
"\n"
"    </body>\n"
"</html>\n"
"";

